ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseurl = "https://mrchypark.github.io/"
languageCode = "ko-KR"
title = "Mrchypark"
theme = "blackburn"
author = "mrchypark"
copyright = "&copy; 2019. All rights reserved."
enableEmoji = true
canonifyurls = true
hasCJKLanguage = true
Paginate = 10


[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "log for you & me | R, Docker, Text analysis etc"
  brand = "Mrchypark"
  googleAnalytics = "UA-47822682-14"
  disqus = "mrchypark"
  # CSS name for highlight.js
  highlightjsVersion = "9.13.1"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
  
  dateFormat = "2006 Jan 02"
  custom_css = ["css/my.css"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Materials"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "material"
    url = "/material/"
  [[menu.main]]
    name = "Packages"
    pre = "<i class='fa fa-cube fa-fw'></i>"
    weight = 4
    identifier = "package"
    url = "/package/"
  [[menu.main]]
    name = "Support"
    pre = "<i class='fa fa-beer fa-fw'></i>"
    weight = 5
    identifier = "support"
    url = "/support/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-address-card fa-fw'></i>"
    weight = 6
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  facebook = "mrchypark"
  github = "mrchypark"
  linkedin = "chanyubpark"
  instagram = "mrchypark"
  twitter = "mrchypark_"
  medium = "mrchypark"
